# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "503dbe31d73d9d77adeb0a596e417eed"
application_url = "https://miller-prostores-refer-andale.trycloudflare.com"
embedded = true
name = "excel-generate"
handle = "excel-generate"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-bed62d0e.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_orders"

[auth]
redirect_urls = [
  "https://miller-prostores-refer-andale.trycloudflare.com/auth/callback",
  "https://miller-prostores-refer-andale.trycloudflare.com/auth/shopify/callback",
  "https://miller-prostores-refer-andale.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
